
ALTER PROCEDURE A10BB
AS
BEGIN

ALTER TABLE FACT
DROP	CONSTRAINT PK_FACT,
		CONSTRAINT FK_FACT_PRODUCT,
		CONSTRAINT FK_FACT_TIME,
		CONSTRAINT FK_FACT_CUSTOMER,
		CONSTRAINT FK_FACT_EMPLOYEE
		
ALTER TABLE PRODUCTDIM
DROP	CONSTRAINT PK_PRODUCTDIM

ALTER TABLE CUSTOMERDIM
DROP	CONSTRAINT PK_CUSTOMERDIM

ALTER TABLE TIMEDIM
DROP	CONSTRAINT PK_TIMEDIM

ALTER TABLE EMPLOYEEDIM
DROP	CONSTRAINT PK_EMPLOYEEDIM

TRUNCATE TABLE FACT
TRUNCATE TABLE PRODUCTDIM
TRUNCATE TABLE CUSTOMERDIM
TRUNCATE TABLE TIMEDIM
TRUNCATE TABLE EMPLOYEEDIM
TRUNCATE TABLE STAGING

ALTER TABLE PRODUCTDIM
ADD CONSTRAINT PK_PRODUCTDIM PRIMARY KEY (ProductID)

ALTER TABLE CUSTOMERDIM
ADD CONSTRAINT PK_CUSTOMERDIM PRIMARY KEY (CustomerID)

ALTER TABLE TIMEDIM
ADD CONSTRAINT PK_TIMEDIM PRIMARY KEY (TimeID)

ALTER TABLE EMPLOYEEDIM
ADD CONSTRAINT PK_EMPLOYEEDIM PRIMARY KEY (EmployeeID)

ALTER TABLE FACT
ADD CONSTRAINT PK_FACT PRIMARY KEY (ProductID, TimeID, CustomerID, EmployeeID),
	CONSTRAINT FK_FACT_PRODUCT FOREIGN KEY (ProductID) REFERENCES PRODUCTDIM,
	CONSTRAINT FK_FACT_TIME FOREIGN KEY (TimeID) REFERENCES TIMEDIM,
	CONSTRAINT FK_FACT_CUSTOMER FOREIGN KEY (CustomerID) REFERENCES CUSTOMERDIM,
	CONSTRAINT FK_FACT_EMPLOYEE FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEEDIM


insert into PRODUCTDIM
SELECT	p.Prod_SKU, p.Prod_Descript, p.Prod_Type, b.Brand_ID, b.Brand_Name, b.Brand_Type
FROM	lgproduct p INNER JOIN lgbrand b ON b.brand_id = p.brand_id	

insert into CUSTOMERDIM
SELECT	C.CUST_CODE, C.CUST_FNAME, C.CUST_LNAME, C.CUST_CITY, C.CUST_STATE, C.CUST_ZIP
FROM	LGCUSTOMER C

insert into TIMEDIM
SELECT INV_DATE, YEAR(INV_DATE), MONTH(INV_DATE), DATEPART(QQ,INV_DATE)
FROM LGINVOICE

insert into EMPLOYEEDIM
SELECT	E.EMP_NUM, E.EMP_FNAME, E.EMP_LNAME, E.EMP_TITLE, D.DEPT_NUM, D.DEPT_NAME
FROM	LGEMPLOYEE E INNER JOIN LGDEPARTMENT D ON E.DEPT_NUM = D.DEPT_NUM


INSERT INTO STAGING (Line_QTY, Line_Price, Cust_Code, Prod_SKU, Inv_Date, Emp_Num)
select	L.LINE_QTY, L.LINE_PRICE, C.CUST_CODE, P.PROD_SKU, I.INV_DATE, E.EMP_NUM
FROM	LGLINE L INNER JOIN LGINVOICE I ON L.INV_NUM = I.INV_NUM
		INNER JOIN LGCUSTOMER C ON C.CUST_CODE = I.CUST_CODE
		INNER JOIN LGEMPLOYEE E ON E.EMP_NUM = I.EMPLOYEE_ID
		INNER JOIN LGPRODUCT P ON P.PROD_SKU = L.PROD_SKU

Update	STAGING
SET		CUSTOMERID = C.CUSTOMERID
FROM	STAGING S INNER JOIN CUSTOMERDIM C ON S.CUST_CODE = C.CUST_CODE
Update	STAGING
SET		TIMEID = T.TIMEID
FROM	STAGING S INNER JOIN TIMEDIM T ON S.INV_DATE = T.INV_DATE

UPDATE	STAGING
SET		ProductID = P.ProductID
FROM	STAGING S INNER JOIN PRODUCTDIM P ON S.PROD_SKU = P.PROD_SKU

UPDATE	STAGING
SET		EmployeeID = E.EmployeeID
FROM	STAGING S INNER JOIN EMPLOYEEDIM E ON S.EMP_NUM = E.EMP_NUM
	

INSERT INTO FACT
SELECT  PRODUCTID, TIMEID, CUSTOMERID, EMPLOYEEID, sum(LINE_QTY), avg(LINE_PRICE)
FROM	STAGING
GROUP BY PRODUCTID, TIMEID, CUSTOMERID, EMPLOYEEID



END

EXEC A10BB

