
UPDATE	LGLINE
SET		LINE_QTY = LINE_QTY - 1
WHERE	INV_NUM = 104 

UPDATE	LGLINE
SET		LINE_QTY = LINE_QTY + 1
WHERE	INV_NUM = 104 

SELECT *
FROM	LGLINE
SELECT	*
FROM LGINVOICE

UPDATE	LGLINE
SET		LINE_QTY = LINE_QTY - 1 
WHERE	INV_NUM = 104
		AND prod_sku = '6041-PBS'
		
UPDATE	LGLINE
SET		LINE_QTY = LINE_QTY + 1 
WHERE	INV_NUM = 104
		AND prod_sku = '6041-PBS'		 

insert into lgline
values (104,4,'8841-JFP',1,6.59) 

delete from Lgline
where inv_num = 104 AND prod_sku = '8841-JFP'



--created trigger
ALTER TRIGGER UPDATE_INV_TOTAL
	ON LGLINE
	AFTER INSERT, DELETE, UPDATE
AS
BEGIN

	DECLARE	@INV_NUM CHAR(4)
	DECLARE	@TOTAL MONEY

	IF(EXISTS (SELECT * FROM INSERTED))
	BEGIN
		
		DECLARE INSERTED_CURSOR CURSOR FOR
		SELECT	INV_NUM, SUM(LINE_QTY*LINE_PRICE) as TOTAL
		FROM	INSERTED
		GROUP BY INV_NUM

		OPEN	INSERTED_CURSOR
		FETCH	NEXT FROM INSERTED_CURSOR
				INTO @INV_NUM, @TOTAL
		WHILE(@@FETCH_STATUS = 0)
		BEGIN
			UPDATE	LGINVOICE
			SET		INV_TOTAL = INV_TOTAL + @TOTAL
			WHERE	INV_NUM = @INV_NUM
			FETCH	NEXT FROM INSERTED_CURSOR
					INTO @INV_NUM, @TOTAL
		END
		CLOSE INSERTED_CURSOR
		DEALLOCATE INSERTED_CURSOR
	END

	IF(EXISTS (SELECT * FROM DELETED))
		BEGIN
			
			DECLARE		DELETED_CURSOR CURSOR FOR
			SELECT		INV_NUM, SUM(LINE_QTY*LINE_PRICE) as TOTAL
			FROM		DELETED
			GROUP BY	INV_NUM
	
			OPEN		DELETED_CURSOR
			FETCH		NEXT FROM DELETED_CURSOR
						INTO @INV_NUM, @TOTAL
			WHILE(@@FETCH_STATUS = 0)
			BEGIN
				UPDATE	LGINVOICE
				SET		INV_TOTAL =INV_TOTAL - @TOTAL
				WHERE	INV_NUM =@INV_NUM
				FETCH	NEXT FROM DELETED_CURSOR
						INTO @INV_NUM, @TOTAL
			END
			CLOSE DELETED_CURSOR
			DEALLOCATE DELETED_CURSOR
		END
	END




		
				